### ISSUE TITLE
New filter stage

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/ngs_mapper#124]
Prior to mapping, (optionally):
1. Drop reads that have a poor index file (__I1__ for __R1__)
2. Drop reads that have Ns

Is it safe to assume the index files reliably named the same (replace R with I?) and in the same directory?

**Comment by necrolyte2** [comment]
This is all merged into Master. Just fixing all the misc test issues and such to get passing builds on travis. Tests pass locally
