### ISSUE TITLE
gzip file support

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/ngs_mapper#151]
Miseq reads come off the machine as gzip'd files and currently the miseq_sync decompresses them into the ReadData directory.

BWA(i believe) supports gzip fastq files already, so we might as well skip the decompression step during miseq_sync and replace that step with a simply symlink(conserves space in so many ways)

Also, some people may have gzip'd files as input

**Comment by averagehat** [comment]
Not sure this is worth it?

**Comment by necrolyte2** [comment]
Probably not

**Comment by necrolyte2** [comment]
Reopening this as AFRIMS now has requested this.
It is apparent that most users will likely not utilize miseq_sync and the likes as we do. This means their data will be raw fastq.gz files.
They can manually unpack the files, but it doesn't seem like it would be too hard to just support gzip format.

**Comment by averagehat** [comment]
Fixed in a5668ae
