### ISSUE TITLE
You should be able to configure samtools/bwa version inside of config.yaml

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/ngs_mapper#17]
Add samtools/bwa/trimmomatic information into config.yaml

**Comment by averagehat** [comment]
Is there a way to do this with anaconda?

**Comment by necrolyte2** [comment]
I think we should just close this issue as the move to miniconda would allow us to specify trimmomatic, bwa, samtools and anything else inside of a requirements file
