### ISSUE TITLE
Make Public

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/ngs_mapper#171]
See #170 

* [x] Switch to open source travis builds
* [x] Enable read the docs
* [ ] Enable coveralls

@InaMBerry 
@mmelendrez

**Comment by necrolyte2** [comment]
Also, @InaMBerry the project is public at this point the other things in this issue are for our development process but anybody can get to the project now with or without a github account.

You can use the following URL for your publication

https://github.com/VDBWRAIR/ngs_mapper

**Comment by averagehat** [comment]
I am not able to add `ngs_mapper` to readthedocs because of rtfd/readthedocs.org#1809. @necrolyte2 you may be able to from your account.

**Comment by averagehat** [comment]
I think coveralls.io may be blocked.

**Comment by necrolyte2** [comment]
Added project manually to readthedocs
It is failing on building matplotlib. Will try this fix
http://blog.rtwilson.com/how-to-make-your-sphinx-documentation-compile-with-readthedocs-when-youre-using-numpy-and-scipy/

**Comment by necrolyte2** [comment]
That didn't work.
I found a flag in the settings to enable --system-site-packages as matplotlib should be installed on the build systems already

**Comment by necrolyte2** [comment]
Related rtfd/readthedocs.org#217

**Comment by necrolyte2** [comment]
Read the docs build worked after enabling system-site-packages option

**Comment by necrolyte2** [comment]
edited readme to include badges. Switched readme to rst to be more standard with our other projects

I'll leave travis/coveralls to you @averagehat 

@InaMBerry you can now view ngs_mapper documentation from anywhere by going to 

http://ngs-mapper.readthedocs.org/en/latest/

**Comment by averagehat** [comment]
travis is up, but I apparently cannot access coveralls.io

**Comment by necrolyte2** [comment]
I put in an ESD ticket to get it unblocked...sigh

**Comment by necrolyte2** [comment]
Think we can close this
