### ISSUE TITLE
Tag all reads

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/ngs_mapper#174]
A lot of tools require *all* reads in a bam file to be tagged, but `tagreads` currently skips some reads. 

https://github.com/VDBWRAIR/ngs_mapper/blob/58761e4b9f7cf5bf01e46ac49ca70ac5f331e283/ngs_mapper/tagreads.py#L56-L59

**Comment by necrolyte2** [comment]
Supplementary reads are skipped because they are not real and it causes
issues
