### ISSUE TITLE
DOI needed for ngs_mapper for citation - please create per instructions

### ISSUE THREAD

**Issue by mmelendrez** [VDBWRAIR/ngs_mapper#180]
Tyghe - 

So because I didn't create this repository it will not allow me to put the DOI in it.

https://guides.github.com/activities/citable-code/

This link has the instructions for getting ngs_mapper a DOI for citing in publication. It's easy, I just can't do it because I'm not powerful enough.

**Comment by necrolyte2** [comment]
[DOI URL](http://dx.doi.org/10.5281/zenodo.46716)
