### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/ngs_mapper#186]
- [x] Primer Trimming
- [x] Using miniconda

#185 
#183

**Comment by necrolyte2** [comment]
See vdbwrair/python_template#20

**Comment by necrolyte2** [comment]
- [ ] version bump
- [ ] look over docs
- [ ] tag release
- [ ] make release branch

**Comment by necrolyte2** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/71
