### ISSUE TITLE
Support sanger ab1 files

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/ngs_mapper#212]
Related to #151 

Again, since there will be no data sync procedure for some users the pipeline should probably convert formats on-the-fly

**Comment by averagehat** [comment]
Could be added to [this](https://github.com/VDBWRAIR/ngs_mapper/blob/410455741d5849fdad517c41174320adb8b38fc7/ngs_mapper/sff_to_fastq.py) which gets called [here](https://github.com/VDBWRAIR/ngs_mapper/blob/410455741d5849fdad517c41174320adb8b38fc7/ngs_mapper/runsample.py#L358)

**Comment by necrolyte2** [comment]
That should work

**Comment by necrolyte2** [comment]
I agree about convert format. I'm wondering how hard it would be to just pass around gzip files though without even extracting them?

**Comment by averagehat** [comment]
I was just reading somewhere that BioPython doesn't support gzip. It's possible that's changed though.

**Comment by necrolyte2** [comment]
Once upon a time I made a thing or found a package that normalized file so
you could do something like

get_fh(handle_or_path)

Where handle or path could be str, open file handle or gzip.open

OK, so then tried this approach with biopython, but then something in their
code looked for specific opened file attribute which gzip.open didn't
have...

**Comment by necrolyte2** [comment]
Anyways, i think if it doesn't support we should consider fixing that for them

**Comment by necrolyte2** [comment]
This works, not sure about other parts of Biopython, but what else do we really use other than maybe switching to using that SeqQual iterator thing(which we have not started using yet)

```
import filehandle
from Bio import SeqIO
print len(list(SeqIO.Parse(*filehandle.open('whatever.fastq.gz'))))
```
