### ISSUE TITLE
Travis: ImportError: No module named _markerlib

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/ngs_mapper#216]
https://travis-ci.org/VDBWRAIR/ngs_mapper/jobs/118045714#L1309
related? ImportError: https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

**Comment by necrolyte2** [comment]
I see sudo Python setup.py install_system_packages in the build log. Did you merge master into this yet

**Comment by averagehat** [comment]
Yeah checkout the diff: https://github.com/VDBWRAIR/ngs_mapper/pull/215/files

**Comment by necrolyte2** [comment]
All the PR's you have(faster-filter and the other one) are not based off of master, they are based off of an old commit and have the old .travis.yml file

I don't know why the PR is not reflecting that. I would expect to see the differences in the travis file as well as everything else, but it is like it only is showing what you changed in the branch not the other way around? Super scary

**Comment by necrolyte2** [comment]
I don't think this is really an issue since it really is stemming from an old 'base' branch
