### ISSUE TITLE
tagreads broken?

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/ngs_mapper#221]
All reads are being tagged as sanger right now it seems

Not sure why

**Comment by necrolyte2** [comment]
I think the regex that is matching miseq reads may be slightly incorrect or something as some of their samples are working as expected and some do not(they show up as sanger instead of MiSeq)

**Comment by necrolyte2** [comment]
Example of MiSeq read being tagged as Sanger

`M01119:15:AARB3:1:1111:23912:25198	163	CPC-0740_USAMRIID_10807bp	3	60	58M	=	3	58	CTGTTGATCTGTGTGAATCAGACTGCGACAGTTCGAGTTTGAAGCGAAAGCTAGCAAC	>AAAAFBFFFFFGGGGGGGGGGHHHHGGGGGGHHGHHHGHGFHHGGEEEGHHHHHHDF	NM:i:1	AS:i:57	XS:i:0	RG:Z:Sanger`

**Comment by averagehat** [comment]
While this issue is still open, did you arrive at those regular expressions by examining the ID's yourself, or some other source?
And I noticed sanger is a catch-all--can it be pretty much anything?

**Comment by necrolyte2** [comment]
So if you Google miseq reads their documentation does not match even our
read names.
So ya, pretty much made the regex based on what I've seen in our read names.
Now, obviously found ours are slightly different than what else is
possible.... Ugg

Sanger names come from whatever the technician specifies so can be anything
ya.
