### ISSUE TITLE
Make correct docs easy to find

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/ngs_mapper#222]
- [x] provide an additional link other than the `readthedocs` badge (and make it clear those docs only apply to specific version)
- [x] include how to build documentation (this got dropped after 9227e9a )

**Comment by necrolyte2** [comment]
I'm not sure including instructions on how to build the docs is necessary now that we have readthedocs available.
I feel like only devs would be the ones building the docs and they shouldn't need docs to tell them how to use sphinx right?

**Comment by averagehat** [comment]
The reason is that someone may be using an older version of ngs_mapper. Unfortunately we can only host docs for the latest version on readthedocs. But if they have the old version and they want the matching docs, their only option to get accurate docs is to build it locally. 

Maybe there's a better way?

**Comment by necrolyte2** [comment]
I think since the project was not open to public we don't have to worry
about older versions right?

**Comment by averagehat** [comment]
Right but if we do update it in a way that changes the usage . . .

**Comment by necrolyte2** [comment]
Ahh, ok I see what you mean now. So if you look at bio bits somehow we
managed to configure it to build every release so users can click on any
release. Was thinking this project did that too. We should make it do that

**Comment by necrolyte2** [comment]
I don't remember ever enabling 'build every version/release' on our other project, but it seems to do it automatically.
I've gone through and told RTD to build a bunch of previous versions so they will now show on the site

**Comment by averagehat** [comment]
fixed in 61cc534 and eaacb53
